import { Student, Payment, DailySession, AuditLog, Course, Section, FeeHead } from '@/types';

export const courses: Course[] = [
  { id: '1', name: 'MPC (Maths, Physics, Chemistry)', code: 'MPC' },
  { id: '2', name: 'BiPC (Biology, Physics, Chemistry)', code: 'BiPC' },
  { id: '3', name: 'CEC (Civics, Economics, Commerce)', code: 'CEC' },
];

export const sections: Section[] = [
  { id: '1', name: 'First Year A', courseId: '1', year: 'First Year' },
  { id: '2', name: 'First Year B', courseId: '1', year: 'First Year' },
  { id: '3', name: 'Second Year A', courseId: '1', year: 'Second Year' },
  { id: '4', name: 'First Year A', courseId: '2', year: 'First Year' },
  { id: '5', name: 'First Year B', courseId: '2', year: 'First Year' },
];

export const feeHeads: FeeHead[] = [
  { id: '1', name: 'Tuition Fee', amount: 35000 },
  { id: '2', name: 'Lab Fee', amount: 8000 },
  { id: '3', name: 'Library Fee', amount: 2000 },
  { id: '4', name: 'Sports Fee', amount: 1500 },
  { id: '5', name: 'Development Fee', amount: 5000 },
];

export const students: Student[] = [
  {
    id: '1',
    rollNumber: 'MPC/2024/001',
    name: 'Aarav Sharma',
    course: 'MPC',
    section: 'First Year A',
    year: 'First Year',
    totalFee: 51500,
    paidAmount: 51500,
    pendingBalance: 0,
    feeStatus: 'Fully Paid',
    parentPhone: '+91 9876543210',
    parentEmail: 'sharma.parent@email.com',
  },
  {
    id: '2',
    rollNumber: 'MPC/2024/002',
    name: 'Diya Patel',
    course: 'MPC',
    section: 'First Year A',
    year: 'First Year',
    totalFee: 51500,
    paidAmount: 30000,
    pendingBalance: 21500,
    feeStatus: 'Partially Paid',
    parentPhone: '+91 9876543211',
    parentEmail: 'patel.parent@email.com',
  },
  {
    id: '3',
    rollNumber: 'BiPC/2024/001',
    name: 'Rohan Kumar',
    course: 'BiPC',
    section: 'First Year A',
    year: 'First Year',
    totalFee: 51500,
    paidAmount: 0,
    pendingBalance: 51500,
    feeStatus: 'Pending',
    parentPhone: '+91 9876543212',
    parentEmail: 'kumar.parent@email.com',
  },
  {
    id: '4',
    rollNumber: 'MPC/2024/003',
    name: 'Ananya Reddy',
    course: 'MPC',
    section: 'First Year B',
    year: 'First Year',
    totalFee: 51500,
    paidAmount: 25000,
    pendingBalance: 26500,
    feeStatus: 'Partially Paid',
    parentPhone: '+91 9876543213',
    parentEmail: 'reddy.parent@email.com',
  },
  {
    id: '5',
    rollNumber: 'BiPC/2024/002',
    name: 'Arjun Singh',
    course: 'BiPC',
    section: 'First Year B',
    year: 'First Year',
    totalFee: 51500,
    paidAmount: 51500,
    pendingBalance: 0,
    feeStatus: 'Fully Paid',
    parentPhone: '+91 9876543214',
    parentEmail: 'singh.parent@email.com',
  },
];

export const payments: Payment[] = [
  {
    id: '1',
    receiptNo: 'RCP/2024/001',
    studentId: '1',
    studentName: 'Aarav Sharma',
    amount: 51500,
    paymentMode: 'UPI',
    remarks: 'Full fee payment for academic year',
    timestamp: new Date('2024-11-01T10:30:00'),
    cashierId: '3',
    cashierName: 'Priya Sharma',
  },
  {
    id: '2',
    receiptNo: 'RCP/2024/002',
    studentId: '2',
    studentName: 'Diya Patel',
    amount: 30000,
    paymentMode: 'Cash',
    remarks: 'Partial payment - first installment',
    timestamp: new Date('2024-11-02T11:15:00'),
    cashierId: '3',
    cashierName: 'Priya Sharma',
  },
  {
    id: '3',
    receiptNo: 'RCP/2024/003',
    studentId: '5',
    studentName: 'Arjun Singh',
    amount: 51500,
    paymentMode: 'Card',
    remarks: 'Full fee payment',
    timestamp: new Date('2024-11-03T09:45:00'),
    cashierId: '3',
    cashierName: 'Priya Sharma',
  },
];

export const dailySessions: DailySession[] = [
  {
    id: '1',
    date: '2024-11-01',
    openedBy: 'Priya Sharma',
    openedAt: new Date('2024-11-01T09:00:00'),
    closedBy: 'Priya Sharma',
    closedAt: new Date('2024-11-01T17:00:00'),
    isOpen: false,
    totalTransactions: 5,
    totalAmount: 145000,
    cashAmount: 60000,
    cardAmount: 40000,
    upiAmount: 45000,
    chequeAmount: 0,
  },
  {
    id: '2',
    date: '2024-11-04',
    openedBy: 'Priya Sharma',
    openedAt: new Date('2024-11-04T09:00:00'),
    isOpen: true,
    totalTransactions: 3,
    totalAmount: 133000,
    cashAmount: 30000,
    cardAmount: 51500,
    upiAmount: 51500,
    chequeAmount: 0,
  },
];

export const auditLogs: AuditLog[] = [
  {
    id: '1',
    timestamp: new Date('2024-11-04T09:00:00'),
    user: 'Priya Sharma',
    role: 'cashier',
    action: 'Day Opening',
    recordId: 'SESSION-2024-11-04',
    details: 'Opened daily session for fee collection',
  },
  {
    id: '2',
    timestamp: new Date('2024-11-04T10:30:00'),
    user: 'Priya Sharma',
    role: 'cashier',
    action: 'Payment Received',
    recordId: 'RCP/2024/001',
    details: 'Collected ₹51,500 from Aarav Sharma via UPI',
  },
  {
    id: '3',
    timestamp: new Date('2024-11-03T15:00:00'),
    user: 'Administrator',
    role: 'admin',
    action: 'Student Created',
    recordId: 'STU-006',
    details: 'Added new student: Vikram Gupta (MPC/2024/004)',
  },
  {
    id: '4',
    timestamp: new Date('2024-11-03T14:30:00'),
    user: 'Dr. Rajesh Kumar',
    role: 'principal',
    action: 'Report Viewed',
    recordId: 'RPT-DAILY-2024-11-03',
    details: 'Accessed daily collection report',
  },
];
